### PR TITLE
use `elts[0]` to access str_code when the rest of `exec` is tuple

### PR DESCRIPTION
**Pull request by spacewander**
People can call `exec` like this: `exec("print(hello world)")`.
They can also call it like this: `exec("print(hello world), global, local")`.

In the first case, the type of `node.body` is string. However, in the second case, the type of `node.body` is tuple. So we need to check if the second case happens and handle it.

Now pigar will correctly parse the file below:
```
#!/usr/bin/env python
# coding: utf-8

exec("import a", {})
```

### CODE REVIEW

**Comment by Damnever** [comment]
Thanks for the PR.

I guess `a.b` is better than `getattr(a, 'b')`，because `a.b` is faster, function call is lower...

**Comment by Damnever** [comment]
I removed the code you added, but testcases still passed:
```
# Sometimes exec statement may be called with tuple in py2
+        elif hasattr(node.body, 'elts') and len(node.body.elts) >= 1:
+            self._str_codes.append(
+                    (getattr(node.body.elts[0], 's'),
+                     node.lineno + self._lineno))
```

Does the code really works?

**Comment by spacewander** [comment]
Maybe there is something related to OS or python version? I found this problem with my Ubuntu. But I can't reproduce it with other systems too... I will test it with ubuntu again tonight.

**Comment by spacewander** [comment]
Seen that it only happens with python 2.7.6
ast

This version of python treats `exec('import a', {}, {})` as a Exec and a Tuple.
The problem can not be found with python 2.7.9. I have not tested with python version < 2.7.6 yet.

**Comment by Damnever** [comment]
That is great, thanks again. I will bring your code back!

**Pull request merged**
